---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: javawebappdeployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: javawebapp
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    minReadySeconds: 60
    template:
      metadata:
        name: javawebapppod
        labels:
          app: javawebapp
    spec:
      containers:
      - image: madhav287/java-app
        name: javawebapp
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: javawebservice
spec:
  type: NodePort
  selector:
    app: javawebapp
  ports:
    - port: 8080
      targetPort: 8080
